### ISSUE TITLE
Output in combination with metafile not working

### ISSUE THREAD

**Issue by s-geiger-si** [fabiospampinato/banal#8]
This is a very useful package. One issue that I have:

I tried to run:
`npx banal --metafile ./dist/my-app/stats.json --output ./analyze/index.html`

This does not work, only `--output-analysis` seems to work, and also if the folder does not exist, we get an ENOENT error.

**Comment by fabiospampinato** [comment]
> if the folder does not exist, we get an ENOENT error.

Just fixed in v1.5.1.

> I tried to run:
npx banal --metafile ./dist/my-app/stats.json --output ./analyze/index.html
> This does not work, only --output-analysis seems to work

`--output` is for outputting the artifacts needed for the analysis, the stuff that you'd find by opening the "temp path" that gets logged when doing something like `npx banal chalk`. In this case those files are not generated because you are starting from a `--metafile` already, so it only makes sense to use `--output-analysis` in combination with that.
